name: test

on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:
    branches:
      - '*'

jobs:
  test-generated-files:
    runs-on: ubuntu-latest

    name: "Run basic tests"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'

      - name: Regenerate files
        run: go generate ./...

      - name: Check git diff
        run: ./.github/commands/fail-on-git-diff.sh

      - name: Test with the Go CLI
        run: go test -short
